# Generated by Django 3.0.7 on 2020-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontWebsiteCTA',
            fields=[
                ('fwcta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwcta_cta_title', models.CharField(max_length=255)),
                ('fwcta_cta_btn_text', models.CharField(max_length=255)),
                ('fwcta_cta_btn_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_pricing_cta',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsiteFeatures',
            fields=[
                ('fwf_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwf_features_title', models.CharField(max_length=255)),
                ('fwf_features_description', models.TextField()),
                ('fwf_features_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_features',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsiteHero',
            fields=[
                ('fwh_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwh_hero_title', models.CharField(max_length=255)),
                ('fwh_hero_subtitle', models.TextField()),
                ('fwh_hero_btn_text', models.CharField(max_length=255)),
                ('fwh_hero_btn_url', models.CharField(max_length=255)),
                ('fwh_hero_banner_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_hero',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsiteInfo',
            fields=[
                ('fwi_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwi_info_title', models.CharField(max_length=255)),
                ('fwi_info_description', models.TextField()),
                ('fwi_info_banner_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_info',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsitePartners',
            fields=[
                ('fwp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwp_partner_image', models.CharField(max_length=255)),
                ('fwp_partner_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_partners',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsitePricingBoxes',
            fields=[
                ('fwpb_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwpb_pricing_boxes_title', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_price_month', models.FloatField()),
                ('fwpb_pricing_boxes_price_year', models.FloatField()),
                ('fwpb_pricing_boxes_f1', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_f1_active', models.BooleanField()),
                ('fwpb_pricing_boxes_f2', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_f2_active', models.BooleanField()),
                ('fwpb_pricing_boxes_f3', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_f3_active', models.BooleanField()),
                ('fwpb_pricing_boxes_f4', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_f4_active', models.BooleanField()),
                ('fwpb_pricing_boxes_f5', models.CharField(max_length=255)),
                ('fwpb_pricing_boxes_f5_active', models.BooleanField()),
            ],
            options={
                'db_table': 'front_website_pricing_boxes',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsitePricingSection',
            fields=[
                ('fwps_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwps_pricing_section_title', models.CharField(max_length=255)),
                ('fwps_pricing_section_description', models.TextField()),
            ],
            options={
                'db_table': 'front_website_pricing_section',
            },
        ),
        migrations.CreateModel(
            name='FrontWebsiteVideo',
            fields=[
                ('fwv_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwv_video_title', models.CharField(max_length=255)),
                ('fwv_video_url', models.CharField(max_length=255)),
                ('fwv_video_cover', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'front_website_video',
            },
        ),
    ]
