# Generated by Django 3.0.7 on 2020-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontwebsitepricingboxes',
            name='fwpb_pricing_boxes_price_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frontwebsitepricingboxes',
            name='fwpb_pricing_boxes_price_year',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
