# Generated by Django 3.0.7 on 2020-06-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arr_app', '0002_auto_20200610_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontWebsiteInfoTitle',
            fields=[
                ('fwit_id', models.AutoField(primary_key=True, serialize=False)),
                ('fwit_title', models.CharField(max_length=255)),
                ('fwit_description', models.TextField()),
            ],
            options={
                'db_table': 'front_website_info_title',
            },
        ),
    ]
