# Generated by Django 3.0.7 on 2020-06-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arr_app', '0003_frontwebsiteinfotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontwebsitepricingsection',
            name='fwps_pricing_section_bottom',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
